Add general navigation components
POP-grupa-K/POP-system-obliczen-wysokoskalowych pull request #74
Opened 2020-11-03 20:50 UTC by lukitoki1

Add app-wide navigation components:
- side NavBar (with ability to shrinking and expanding),
- TopBar.

Resolves #67

2020-11-03 21:00 UTC, maciekkoz98 requested changes

2020-11-03 21:00 UTC, maciekkoz98 commented on frontend/compute-system/src/App.tsx
> +import {createBrowserHistory} from "history";
use Prettier as code formatter. It does the job quite nice!

2020-11-03 21:00 UTC, maciekkoz98 commented on frontend/compute-system/src/components/Navigation/NavDrawer/NavDrawer.tsx
> +);
I would extract style lines into separate file

2020-11-03 21:00 UTC, maciekkoz98 commented on frontend/compute-system/src/components/Navigation/NavDrawer/TopBar.tsx
> +const useStyles = makeStyles((theme: Theme) =>
I would extract style lines to separate file

2020-11-03 21:00 UTC, maciekkoz98 commented on frontend/compute-system/src/App.tsx
> +          <Navigation>
Can it be a parent of Router rather than AppStore?
Thanks to that every other route would have the drawer and the topbar

2020-11-03 21:03 UTC, lukitoki1 commented on frontend/compute-system/src/App.tsx
> +          <Navigation>
Yep, good idea.

2020-11-03 21:04 UTC, lukitoki1 commented on frontend/compute-system/src/App.tsx
> +import {createBrowserHistory} from "history";
I'm aware of the fact that this is a typical Prettier styling, but then Prettier should be added to dev dependencies imo.

2020-11-03 21:07 UTC, maciekkoz98 commented on frontend/compute-system/src/App.tsx
> +import {createBrowserHistory} from "history";
how to add it then? ;p

2020-11-03 21:09 UTC, lukitoki1 commented on frontend/compute-system/src/App.tsx
> +import {createBrowserHistory} from "history";
well, I'm working on it xd

2020-11-03 21:29 UTC, lukitoki1 commented on frontend/compute-system/src/App.tsx
> +import {createBrowserHistory} from "history";
DONE

2020-11-03 21:29 UTC, lukitoki1 commented on frontend/compute-system/src/App.tsx
> +          <Navigation>
DONE
DONE

2020-11-03 21:30 UTC, lukitoki1 commented on frontend/compute-system/src/components/Navigation/NavDrawer/TopBar.tsx
> +const useStyles = makeStyles((theme: Theme) =>
DONE
DONE
DONE

2020-11-03 21:30 UTC, lukitoki1 commented on frontend/compute-system/src/components/Navigation/NavDrawer/NavDrawer.tsx
> +);
DONE
DONE
DONE
DONE

2020-11-03 21:41 UTC, maciekkoz98 requested changes
pierdolety left

2020-11-03 21:41 UTC, maciekkoz98 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +);
breakline here

2020-11-03 21:41 UTC, maciekkoz98 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +);
breakline here

2020-11-03 21:41 UTC, maciekkoz98 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +);
breakline here

2020-11-03 21:41 UTC, maciekkoz98 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +};
breakline here

2020-11-03 21:49 UTC, lukitoki1 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +);
DONEDONE

2020-11-03 21:49 UTC, lukitoki1 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +);
DONEDONEDONEDONE

2020-11-03 21:49 UTC, lukitoki1 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +};
DONEDONEDONEDONEDONEDONE

2020-11-03 21:49 UTC, lukitoki1 commented on frontend/compute-system/src/components/Navigation/styles.ts
> +);
DONEDONEDONEDONEDONEDONEDONEDONE

2020-11-03 21:52 UTC, maciekkoz98 approved these changes

2020-11-04 08:34 UTC, KonradMagiera approved these changes

2020-11-04 09:19 UTC, merged